name: Cypress CI/CD

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pramudya Testing
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/1941720054_PramudyaWibowo/*

      - name: Risang Testing
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/1941720166_RisangDaniswara/*
          
      - name: Zulfan Testing
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/1941720142_MohZulfanAkbar/*
          
      - name: Erika Testing
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/1941720015_ErikaAmalia/*
          
      - name: Tasya Testing
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/1941720105_TasyaRachmahSakinah/*
